Month 12/step 1
Karkachevich/algososh_mbou pull request #78
Opened 2022-10-20 09:20 UTC by Karkachevich

2022-10-20 12:05 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Используются функциональные компоненты;

### **Но есть несколько замечаний, которые нужно исправить:**

- По чек-листу. Функции, которые реализуют работу алгоритмов и не взаимодействуют с компонентом, вынесены в отдельные файлы utils.ts в папке соответствующего компонента; Проверьте во всём проекте.

- По чек-листу. Классы, описывающие работу структур данных, вынесены в отдельные файлы в папке соответствующего компонента.

- Строка

  - У вас не отображаются элементы.
    https://disk.yandex.ru/i/yUc2UvPnwh8bHQ

- Стек

  Правильный вариант: https://disk.yandex.ru/d/tABGjbd0cfJoiQ;
  Ваш вариант: https://disk.yandex.ru/i/JT_bRsyrA-8-Wg;

  - исправьте поведение кнопок, они должны быть в состоянии disabled, когда поле пустое.

  - исправьте поведение элементов, По чек-листу: при нажатии кнопки «Удалить» элемент в вершине стека на короткое время выделяется цветом, а затем удаляется из стека. У вас же, загорается предыдущий элемент.

  - Не забывайте делать кнопки не активными во время каких-то действий, а то происходят вот такие баги (Они продемонстрированы на видео).

- Очередь

  - Алгоритм работает неверно, при нажатии кнопки «Добавить» в очередь добавляется элемент со значением из поля ввода, а поле ввода очищается. Добавленный элемент должен попадать в конец очереди, а у вас каждый раз очередь начинается сначала https://disk.yandex.ru/i/kmV0gRDlIhR1CQ

  - У вас неправильно появляются надписи "top" и "tail", когда в очередь добавляется первый элемент. Над ним должны быть обе надписи, а потом уже "tail" переезжает дальше.

  - Если мы заполним всю очередь, а потом добавим 1 элемент, то у нас начнётся бесконечная загрузка. Поэтому лучше запретить добавлять новые элементы когда вся очередь будет заполнена. Ниже записал видео, чтобы было понятно что я имею ввиду:

    - как это работает у вас: https://disk.yandex.ru/d/fcG4kdQ8mVwUww;
    - как это должно работать правильно: https://disk.yandex.ru/i/4p-B66yaQjeHeg;

- Связный список

  Как это должно работать правильно: https://disk.yandex.ru/i/cv6sV6I-f48CYg;
  Как это работает у вас: https://disk.yandex.ru/i/32FOAVNMXAM-hQ;

  - На видео видно, что при удалении есть какие-то подергивания, посмотрите из-за чего они вызваны, и исправьте их.

  - У вас не отображаются элементы.

  - Если полностью его очистить (кнопками "удалить их head|tail"), то перестаёт работать функционал, и начинается бесконечная загрузка.

### **Сделает код лучше:**

- Лучше реализовывать удаление таймера/интервала при размонтировании компонента, иначе возможны ошибки/баги когда компонент размонтируется, а таймер всё равно сработает.

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить".**

2022-10-20 12:05 UTC, ArslanDev666 commented on src/utils/bubble-sorting.ts
> +      await delay(SHORT_DELAY_IN_MS);
**Можно лучше:** Здесь и далее. Стоит создать функции сортировки таким образом, чтобы они возвращали набор шагов и далее при отображении алгоритма добавлять паузы между шагами, а не генерировать паузы непосредственно в алгоритме.

2022-10-21 19:42 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодец!**

### **Но 1 большое замечание, которое нужно исправить:**

- Не нужно менять стейт от `useState` напрямую. Проверьте и исправьте во всём проекте. https://reactjs.org/docs/state-and-lifecycle.html#do-not-modify-state-directly.

### **Сделает код лучше:**

- удалить остаточный файл app.test.tsx, он остался от create-react-app.

- Вынести классы, описывающие работу структур данных, в файлик с названием класса, а не utils.js. В utils.js нужно помещать только те функции, которые никак не взаимодействуют со стейтом компонента.

- Если полностью очистить Связный список (кнопками "удалить их head|tail"), то перестаёт работать функционал. Реализуйте функционал так, чтобы можно было после полного удаления списка, добавлять новые элементы.

2022-10-21 19:42 UTC, ArslanDev666 commented on src/components/stack-page/stack-page.tsx
> +    };
**Надо исправить:** Не стоит изменять стейт напрямую, используйте для этого setState(). Вот почему нельзя делать это напрямую: https://reactjs.org/docs/state-and-lifecycle.html#do-not-modify-state-directly. Проверьте и исправьте во всём проекте. У вас во многих файлах повторяется такая ошибка.

2022-10-21 19:42 UTC, ArslanDev666 commented on src/components/stack-page/stack-page.tsx
> +  };
**Надо исправить:** тут тоже нужно ставить лоадинг `inProgress`. А также не забудьте добавить `inProgress` в `disabled` у кнопки "удалить". Иначе у вас могут быть различные баги.

2022-10-22 11:03 UTC, Karkachevich commented on src/components/stack-page/stack-page.tsx
> +    };
Здесь я не понял! state это ключ свойства объекта как head или value, соответственно стейт от useState на прямую я ни где не меняю.

2022-10-22 17:10 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

### **Вы молодец! Работа принята, удачи в дальнейшем обучении.**

### **Сделает код лучше:**

- "Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE. (Отметил места в коде);

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

2022-10-22 17:10 UTC, ArslanDev666 commented on src/components/queue-page/queue-page.tsx
> +  const size: number = 7;
**можно лучше:** "Магические" значения лучше вынести в константу.

2022-10-22 17:10 UTC, ArslanDev666 commented on src/components/queue-page/queue-page.tsx
> +      setCharsArr([...newArr]);
**Можно лучше:** здесь и в других похожих местах. Тут можно сразу указывать `setCharsArr(newArr)`, т.к newArr и так будет массивом.

2022-10-22 17:10 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +  const size: number = 4;
**можно лучше:** "Магические" значения лучше вынести в константу.

2022-10-22 17:10 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +    if (value <= 0 || value > 19) {
**можно лучше:** "Магические" значения лучше вынести в константу.

2022-10-22 17:10 UTC, ArslanDev666 commented on src/components/stack-page/stack-page.tsx
> +          maxLength={4}
**можно лучше:** "Магические" значения лучше вынести в константу.

2022-10-22 17:10 UTC, ArslanDev666 commented on src/components/string-page/string-page.tsx
> +          maxLength={11}
**можно лучше:** "Магические" значения лучше вынести в константу.

2022-10-22 17:10 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +          max={19}
**можно лучше:** "Магические" значения лучше вынести в константу.

2022-10-22 17:10 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +          maxLength={4}
**можно лучше:** "Магические" значения лучше вынести в константу.

2022-10-22 17:10 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +          maxLength={1}
**можно лучше:** "Магические" значения лучше вынести в константу.

2022-10-24 06:05 UTC, merged